### ISSUE TITLE
applio?

### ISSUE THREAD

**Issue by blaisewf** [Husky110/rvc_web_ui-docker#1]
🥹 https://github.com/iahispano/applio

**Comment by Husky110** [comment]
Is that a request for an image-tag to this or how should I interpred that link? :)

**Comment by blaisewf** [comment]
> Is that a request for an image-tag to this or how should I interpred that link? :)

Yes

**Comment by Husky110** [comment]
I will see what I can do, but no promisses right now, cause I've never used Applio before and I would have the same standards (easy to use) as with the RVC_WebUI-Tags...

**Comment by Husky110** [comment]
@blaise-tk - can I use the rvc/lib/tools/prerequisites_download.py just by running `python rvc/lib/tools/prerequisites_download.py` and it works?

**Comment by blaisewf** [comment]
i recommend you run it though the cli

**Comment by Husky110** [comment]
Wrote you on Discord.

**Comment by Husky110** [comment]
Waiting for TestResults. The tag is there. If there are any problems, please write on Discord or open a new issue.
